// <auto-generated />
using System;
using FundamentosEFPlatzi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FundamentosEFPlatzi.Migrations
{
    [DbContext(typeof(TareaContext))]
    [Migration("20220311195331_seedData")]
    partial class seedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FundamentosEFPlatzi.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("ef6e255a-d835-48b0-87f4-4e33d138db5e"),
                            Nombre = "Pendientes",
                            Peso = 0
                        },
                        new
                        {
                            CategoriaId = new Guid("46a837b2-ce88-4304-82fb-b574d23c1e3e"),
                            Nombre = "Actividad personal",
                            Peso = 0
                        });
                });

            modelBuilder.Entity("FundamentosEFPlatzi.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("33fd29d5-7bb4-4b54-85a1-e4348613c2e7"),
                            CategoriaId = new Guid("ef6e255a-d835-48b0-87f4-4e33d138db5e"),
                            FechaCreacion = new DateTime(2022, 3, 11, 14, 53, 31, 65, DateTimeKind.Local).AddTicks(5894),
                            PrioridadTarea = 2,
                            Titulo = "Revisar la tesis de grado"
                        },
                        new
                        {
                            TareaId = new Guid("c15dd6dc-aad8-4470-a23c-c3b84238fc72"),
                            CategoriaId = new Guid("46a837b2-ce88-4304-82fb-b574d23c1e3e"),
                            FechaCreacion = new DateTime(2022, 3, 11, 14, 53, 31, 65, DateTimeKind.Local).AddTicks(5904),
                            PrioridadTarea = 0,
                            Titulo = "Comprar nuevo comic de batman"
                        });
                });

            modelBuilder.Entity("FundamentosEFPlatzi.Tarea", b =>
                {
                    b.HasOne("FundamentosEFPlatzi.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("FundamentosEFPlatzi.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
